### ISSUE TITLE
Usage

### ISSUE THREAD

**Issue by jo-project** [0x5eal/clap.luau#1]
Hey, can you tell me how to use this?

**Comment by CompeyDev** [comment]
It's not currently complete, and heavily bug-prone so I wouldn't recommend using it ATM. But if you want to try it out nonetheless, see [examples/helloWorld.luau](https://github.com/0x5eal/clap.luau/blob/d3a4734cd89a465c8708101c8f916f98ad5d463a/examples/helloWorld.luau).

Also note that this is highly subject to change, and the API surface may change at any time.
